- name: "Provision Image"
  hosts: default

  tasks:
    - name: Add Gitlab runner PPA
      shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash

    - name: Install Packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - git
        - gitlab-runner
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
        - software-properties-common
      become: yes

    - name: Add docker engine PPA
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Add docker engine repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      become: yes

    - name: Install Docker
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      become: yes

    - name: Install Docker Machine
      shell: |
        base=https://github.com/docker/machine/releases/download/v0.16.0
        curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine
        mv /tmp/docker-machine /usr/local/bin/docker-machine
        chmod +x /usr/local/bin/docker-machine
      become: yes
